proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}


setup


set test "--too<TAB> should complete \"--tool=\""
assert_complete "--tool=" "valgrind --too" $test -nospace


sync_after_int


# should complete tool names
set test "--tool=memche<TAB> should complete \"memcheck\""
assert_complete "--tool=memcheck" "valgrind --tool=memche" $test


sync_after_int


# should complete options for other than default tool
set test "--tool=helgrind --history-l<TAB> should complete \"--history-level=\""
assert_complete "--history-level=" "valgrind --tool=helgrind --history-l" $test -nospace


sync_after_int


set test "file --<TAB> should complete file's options"
assert_complete "--magic-file" "valgrind --tool=helgrind --history-level=full file --magic-fi" $test


sync_after_int


set test "it should be possible to complete file paths"
set dir $::srcdir/fixtures/shared
set files [split [exec bash -c "cd $dir/bin && ls -p"] "\n"]
assert_complete_dir $files "valgrind --log-file=val.log ./bin/" $dir $test


sync_after_int


teardown
